### ISSUE TITLE
Does not work in WSL with Ubuntu

### ISSUE THREAD

**Issue by lukebarone** [dmorady1/youtube-subscriptions-parser-json#1]
WSL running Ubuntu, with Python 3.6. Errors out with the following after running the install:

```nolang
$ python3 ./youtube-json-parse.py                                                                                                             Traceback (most recent call last):
  File "./youtube-json-parse.py", line 87, in <module>
    main()
  File "./youtube-json-parse.py", line 24, in main
    driver = webdriver.Chrome('./chromedriver_1') # local driver
  File "/home/luke/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/luke/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)                                                                                           File "/home/luke/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session                         response = self.execute(Command.NEW_SESSION, parameters)                                                                                    File "/home/luke/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute                               self.error_handler.check_response(response)                                                                                                 File "/home/luke/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response                     raise exception_class(message, screen, stacktrace)                                                                                        selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.                                         (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

**Comment by dmorady1** [comment]
Hello, did it install all the software? Were there some problems? 

It looks like to me you used a chromedriver which you downloaded on your own? `'./chromedriver_1'` 
 from my script it should download the chromedriver 

Maybe you can try to do the following explained on this site if you use your self downloaded chromedriver
https://www.devzoneoriginal.com/2020/07/solved-error-devtoolsactiveport-file.html

**Comment by lukebarone** [comment]
As far as I know, it installed correctly - there were no errors.

I tried the Linux driver, the Windows driver, and one that I used before with Selenium. I tried the page you linked to, but it's failing as `options` is not defined.

I'm sorry, but I know I'm very new at Python.

**Comment by dmorady1** [comment]
Hello, sorry for the late response. 

I updated the repo, so please make sure to clone or pull the repo again.
I added a [windows](https://github.com/dmorady1/youtube-subscriptions-parser-json/blob/main/windows.md) installation section,
where it is written how it should work under windows. Hope it works then for you :)

**Comment by dmorady1** [comment]
I just updated my program, it should now be able to download the correct chromedriver automatically, if any help is still needed please make a new issue. I hope this little script  worked for you :)
